---
abstract: 'Parse and format time values'
author:
  - 'David Muir Sharnoff <cpan@dave.sharnoff.org>'
build_requires:
  Time::Piece: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.62, CPAN::Meta::Converter version 2.112150'
license: unknown
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Time-ParseDate
no_index:
  directory:
    - t
    - inc
requires: {}
resources:
  repository: http://github.com/muir/Time-modules
version: 2015.103
